sonar.projectKey=SE2-Machi-Koro_Server
sonar.organization=se2-machi-koro
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/kotlin,src/main/resources
sonar.tests=src/test/kotlin
sonar.test.inclusions=src/test/kotlin/**/*.kt

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.coverage.exclusions=src/main/kotlin/**/dto/**,src/main/kotlin/**/config/**,src/main/kotlin/**/ServerApplication.kt

sonar.newCode.referenceBranch=main

sonar.qualitygate.wait=true